### ISSUE TITLE
Spawned Phase II missions are un-takeable

### ISSUE THREAD

**Issue by cjshawMIT** [wombats-writing-code/fbw-instructor#1]
```
INFO 2016-12-13 11:57:20,782 general 20428 139645216089856 An exception of type IllegalState occurred in Traceback (most recent call last):
  File "/var/www/webapps/qbank/assessmentsv2/views.py", line 2520, in get
    taken._update_available_sections()
  File "/var/www/webapps/qbank/dlkit/mongo/assessment/objects.py", line 2569, in _update_available_sections
    section_id = self._get_first_assessment_section().get_id()
  File "/var/www/webapps/qbank/dlkit/mongo/assessment/objects.py", line 2592, in _get_first_assessment_section
    first_part_id = get_first_part_id_for_assessment(assessment_id, runtime=self._runtime, proxy=self._proxy)
  File "/var/www/webapps/qbank/dlkit/mongo/assessment/assessment_utilities.py", line 49, in get_first_part_id_for_assessment
    return get_next_part_id(assessment_id, runtime, proxy, sequestered=False)[0]
  File "/var/www/webapps/qbank/dlkit/mongo/assessment/assessment_utilities.py", line 115, in get_next_part_id
    raise IllegalState('No next AssessmentPart is available for part_id')
IllegalState: No next AssessmentPart is available for part_id
. Arguments:
('No next AssessmentPart is available for part_id',)
```

**Comment by cjshawMIT** [comment]
This seems to work with newly-spawned Phase II missions (just tested with `Cole test mission`), so perhaps it was a remnant of separating sections and questions. Let's monitor it...

**Comment by luwen-huang** [comment]
actually, spawned phase II missions don't show up anymore on student view. Try:
1) create a new mission on Instructor
2) take that new mission on Student
3) go back to Instructor and spawn Phase II
4) ---> the spawned mission doesn't show up on Student.

**Comment by cjshawMIT** [comment]
I think this is a different issue than the one I opened the issue for…I’d prefer to make a separate issue to track this.

**Comment by cjshawMIT** [comment]
I think this is a different issue than the one I opened the issue for…I’d prefer to make a separate issue to track this.

**Comment by cjshawMIT** [comment]
I've been testing phase 2 missions and they seem to work (for visitors).

**Comment by cjshawMIT** [comment]
For @luwen-huang 's other reported issue, refer to #41 in student app.
